export const REVEALS = {
  leading_coefficient: {
    conceptId: 'leading_coefficient',
    title: 'The Leading Coefficient',
    subtitle: 'You just used y = ax²',
    body: [
      'The number <b>a</b> in y = ax² is called the <b>leading coefficient</b>.',
      'It controls how wide or narrow the parabola opens:',
      '• Bigger |a| → narrower arc (steeper descent)',
      '• Smaller |a| → wider arc (gentler descent)',
      '• Negative a → parabola opens downward',
      '',
      'Every parabola you\'ve seen so far is just y = ax² with a different a.',
    ].join('\n'),
    vocabulary: ['leading coefficient', 'vertical stretch', 'compression'],
  },

  negative_a_intro: {
    conceptId: 'negative_a_intro',
    title: 'Negative a — Upside Down',
    subtitle: 'Flipping the parabola',
    body: [
      'When <b>a is negative</b>, the parabola opens <b>downward</b>.',
      'When <b>a is positive</b>, it opens <b>upward</b>.',
      '',
      'Same shape — just reflected over its vertex.',
      '',
      '→ Negative a = <b>frown</b> (opens down)',
      '→ Positive a = <b>smile</b> (opens up)',
    ].join('\n'),
    vocabulary: ['reflection', 'concave up', 'concave down'],
  },

  vertex_form: {
    conceptId: 'vertex_form',
    title: 'The Vertex',
    subtitle: 'y = a(x − h)² + k',
    body: [
      'Every parabola has a <b>vertex</b> — its highest or lowest point.',
      '',
      'In y = a(x − h)² + k, the vertex is the point <b>(h, k)</b>.',
      '',
      '• <b>h</b> shifts the parabola left or right',
      '• <b>k</b> shifts it up or down',
      '',
      'This is called <b>vertex form</b> because h and k directly give you the vertex.',
    ].join('\n'),
    vocabulary: ['vertex', 'axis of symmetry', 'horizontal shift', 'vertical shift'],
  },

  negative_a: {
    conceptId: 'negative_a',
    title: 'The Sign of a',
    subtitle: 'Smile vs. frown',
    body: [
      'The <b>sign of a</b> tells you which way the parabola opens:',
      '',
      '• <b>a > 0</b> → opens upward (U-shape, smile ☺)',
      '• <b>a < 0</b> → opens downward (∩-shape, frown ☹)',
      '',
      'The <b>magnitude</b> of a (|a|) controls width.',
      'The <b>sign</b> of a controls orientation.',
    ].join('\n'),
    vocabulary: ['leading coefficient', 'orientation', 'concavity'],
  },

  factored_form: {
    conceptId: 'factored_form',
    title: 'Roots — Where the Arc Lands',
    subtitle: 'y = a(x − r₁)(x − r₂)',
    body: [
      'The <b>roots</b> r₁ and r₂ are where y = 0 — where the arc crosses the x-axis.',
      '',
      'Factored form y = a(x − r₁)(x − r₂) puts those landing points front and center.',
      '',
      'Every quadratic with two real roots can be written this way.',
      '',
      '→ Set r₂ to match the target\'s x, and the arc lands there.',
    ].join('\n'),
    vocabulary: ['roots', 'zeros', 'factored form', 'x-intercepts'],
  },

  standard_form: {
    conceptId: 'standard_form',
    title: 'Standard Form',
    subtitle: 'y = ax² + bx + c',
    body: [
      'All three forms — vertex, factored, standard — describe the <b>same parabola</b>.',
      '',
      'Standard form y = ax² + bx + c tells you:',
      '• <b>a</b>: shape and direction (same as always)',
      '• <b>c</b>: the y-intercept (height at x = 0)',
      '• <b>b</b>: the slope at the launch point',
      '',
      'You can convert between forms using algebra.',
      'They\'re just different ways of looking at the same curve.',
    ].join('\n'),
    vocabulary: ['standard form', 'y-intercept', 'equivalent forms', 'completing the square'],
  },

  multi_shot_strategy: {
    conceptId: 'multi_shot_strategy',
    title: 'Multi-Shot Strategy',
    subtitle: 'One equation at a time',
    body: [
      'Sometimes one equation isn\'t enough.',
      '',
      'In multi-shot levels, you launch multiple projectiles — each with its own equation.',
      'Use your first shot to clear the path, and your second to hit the target.',
      '',
      'Think of it as solving a system: each equation does a different job.',
    ].join('\n'),
    vocabulary: ['system of equations', 'multi-shot', 'strategic launch'],
  },

  cubic_intro: {
    conceptId: 'cubic_intro',
    title: 'Beyond Parabolas: Cubic Functions',
    subtitle: 'y = a(x − h)³ + k',
    body: [
      'Not every path is a parabola.',
      '',
      'Cubic functions like y = a(x−h)³ + k create S-shaped curves that can loop around obstacles.',
      '',
      'The cube (³) means the curve can change direction — going up, then leveling, then up again.',
      '',
      'This opens up entirely new paths that parabolas can\'t reach.',
    ].join('\n'),
    vocabulary: ['cubic function', 'inflection point', 'S-curve', 'degree'],
  },

  roots_and_zeros: {
    conceptId: 'roots_and_zeros',
    title: 'Roots, Zeros, and x-Intercepts',
    subtitle: 'Three names for the same thing',
    body: [
      'The <b>roots</b> of a quadratic are the x-values where y = 0.',
      'They\'re also called <b>zeros</b> or <b>x-intercepts</b> — same thing, different names.',
      '',
      'In factored form y = a(x − r₁)(x − r₂):',
      '• The roots are <b>r₁</b> and <b>r₂</b>',
      '• The axis of symmetry is at x = <b>(r₁ + r₂) / 2</b>',
      '• The vertex is always exactly between the roots',
      '',
      'If you know where the arc starts and where it lands, you know the roots — and that\'s enough to define the entire parabola.',
    ].join('\n'),
    vocabulary: ['roots', 'zeros', 'x-intercepts', 'axis of symmetry'],
  },

  vertex_to_factored: {
    conceptId: 'vertex_to_factored',
    title: 'Connecting the Forms',
    subtitle: 'Vertex ↔ Factored ↔ Standard',
    body: [
      'Every parabola can be written three ways:',
      '',
      '• <b>Vertex form</b>: y = a(x−h)² + k → tells you the peak',
      '• <b>Factored form</b>: y = a(x−r₁)(x−r₂) → tells you the landing points',
      '• <b>Standard form</b>: y = ax² + bx + c → tells you the y-intercept',
      '',
      'They\'re all the same curve — just different information highlighted.',
      'Converting between them is algebra: expanding, factoring, completing the square.',
    ].join('\n'),
    vocabulary: ['equivalent forms', 'expanding', 'factoring', 'completing the square'],
  },

  what_is_a_function: {
    conceptId: 'what_is_a_function',
    title: 'What Is a Function?',
    subtitle: 'Input → Output',
    body: [
      'A <b>function</b> is a rule: put a number in, get exactly one number out.',
      '',
      'Like a vending machine — press A3, get a specific snack. Same button, same snack, every time.',
      '',
      'y = ax² is a function: put in an x, get out a y.',
      'Change <b>a</b>, and the rule changes — different outputs for the same inputs.',
      '',
      'Functions are the backbone of math, physics, engineering, and this game.',
    ].join('\n'),
    vocabulary: ['function', 'input', 'output', 'domain', 'range'],
  },

  symmetry: {
    conceptId: 'symmetry',
    title: 'Symmetry of Parabolas',
    subtitle: 'Mirror, mirror',
    body: [
      'Every parabola has a <b>line of symmetry</b> — an invisible mirror down the middle.',
      '',
      'For y = ax², the line of symmetry is the y-axis (x = 0).',
      'For y = a(x−h)² + k, it shifts to x = h.',
      '',
      'Why it matters: the left half is always a mirror of the right half.',
      'Know one side, and you know the whole thing.',
    ].join('\n'),
    vocabulary: ['symmetry', 'axis of symmetry', 'line of symmetry', 'mirror'],
  },

  horizontal_shift: {
    conceptId: 'horizontal_shift',
    title: 'Horizontal Shift',
    subtitle: 'Moving the arc left and right',
    body: [
      'In y = a(x − h)² + k, the <b>h</b> value slides the entire parabola sideways.',
      '',
      'It feels backwards: <b>(x − 3)</b> shifts RIGHT, not left.',
      'That\'s because you\'re asking "what x makes the inside zero?" — and that\'s x = 3.',
      '',
      'This "backwards" feeling confuses everyone at first.',
      'Think of it as: the vertex moves to where h tells it to go.',
    ].join('\n'),
    vocabulary: ['horizontal shift', 'translation', 'vertex'],
  },

  vertex_hunting: {
    conceptId: 'vertex_hunting',
    subtitle: 'Finding the peak',
    title: 'Vertex Hunting',
    body: [
      'The <b>vertex</b> is the most important point on a parabola.',
      '',
      'In vertex form, it\'s easy: (h, k). Done.',
      'In standard form y = ax² + bx + c, the vertex is at x = <b>−b / 2a</b>.',
      '',
      'Plug that x back in to get the y-value.',
      '',
      'The vertex tells you the maximum height of a projectile, the minimum cost of a product, the peak of a satellite\'s orbit.',
    ].join('\n'),
    vocabulary: ['vertex', 'maximum', 'minimum', 'optimization'],
  },

  real_world_parabolas: {
    conceptId: 'real_world_parabolas',
    title: 'Parabolas in the Real World',
    subtitle: 'They\'re everywhere',
    body: [
      'Parabolas show up constantly in nature and engineering:',
      '',
      '• <b>Projectile motion</b> — anything thrown follows a parabolic arc',
      '• <b>Satellite dishes</b> — shaped to focus signals at one point',
      '• <b>Headlights</b> — the reflector is a parabola, light bounces forward',
      '• <b>Suspension bridges</b> — the cables hang in parabolic curves',
      '',
      'Every time you throw a ball, you\'re creating a parabola.',
      'Now you know the math behind it.',
    ].join('\n'),
    vocabulary: ['projectile motion', 'focus', 'reflector', 'applications'],
  },

  wider_vs_narrower: {
    conceptId: 'wider_vs_narrower',
    title: 'Width and Steepness',
    subtitle: 'Why |a| matters',
    body: [
      '<b>|a| > 1</b>: the parabola is <b>narrower</b> than y = x².',
      '<b>|a| < 1</b>: the parabola is <b>wider</b> than y = x².',
      '<b>|a| = 1</b>: exactly y = x².',
      '',
      'In the game: a bigger |a| means a steeper, shorter-range arc.',
      'A smaller |a| means a flatter, longer-range arc.',
      '',
      'This is called <b>vertical stretch</b> — it\'s like pulling the curve taller or squishing it shorter.',
    ].join('\n'),
    vocabulary: ['vertical stretch', 'compression', 'dilation', 'coefficient'],
  },

  domain_and_range: {
    conceptId: 'domain_and_range',
    title: 'Domain & Range',
    subtitle: 'What goes in, what comes out',
    body: [
      'The <b>domain</b> is all valid inputs (x-values).',
      'The <b>range</b> is all possible outputs (y-values).',
      '',
      'For y = ax² (a > 0):',
      '• Domain: all real numbers',
      '• Range: y ≥ 0 (the parabola never goes below zero)',
      '',
      'In the game, your domain is the distance the ball travels (0 to the edge).',
      'Your range is how high — or low — the arc reaches.',
    ].join('\n'),
    vocabulary: ['domain', 'range', 'input', 'output'],
  },

  discriminant: {
    conceptId: 'discriminant',
    title: 'The Discriminant',
    subtitle: 'Will it hit the ground?',
    body: [
      'The <b>discriminant</b> is b² − 4ac (from standard form ax² + bx + c).',
      '',
      'It tells you how many roots a quadratic has:',
      '• <b>Positive</b> → 2 real roots (arc crosses the ground twice)',
      '• <b>Zero</b> → 1 root (arc just touches the ground)',
      '• <b>Negative</b> → no real roots (arc never touches the ground!)',
      '',
      'In the game, a negative discriminant means your shot flies over everything.',
      'Math predicts physics.',
    ].join('\n'),
    vocabulary: ['discriminant', 'real roots', 'quadratic formula'],
  },

  multiple_roots: {
    conceptId: 'multiple_roots',
    title: 'Multiple Roots, Multiple Paths',
    subtitle: 'Choosing your landing spot',
    body: [
      'When a quadratic has two roots, your arc hits the ground at two points.',
      '',
      'In factored form, you choose exactly where:',
      '• r₁ is where the arc starts (usually behind you)',
      '• r₂ is where it lands (your target)',
      '',
      'You can also flip it — aim for a closer root and use the other end of the arc.',
      'Two roots = two possible strategies.',
    ].join('\n'),
    vocabulary: ['roots', 'strategy', 'targeting', 'path selection'],
  },

  completing_the_square: {
    conceptId: 'completing_the_square',
    title: 'Completing the Square',
    subtitle: 'Standard → Vertex form',
    body: [
      'You can convert <b>standard form</b> to <b>vertex form</b> by completing the square.',
      '',
      'y = ax² + bx + c',
      'y = a(x² + b/a·x) + c',
      'y = a(x + b/2a)² − b²/4a + c',
      '',
      'Now it\'s in vertex form with h = −b/2a and k = c − b²/4a.',
      '',
      'This isn\'t just algebra tricks — it\'s how you find the peak of any parabola from any starting equation.',
    ].join('\n'),
    vocabulary: ['completing the square', 'conversion', 'algebra', 'vertex form'],
  },

  accuracy_and_efficiency: {
    conceptId: 'accuracy_and_efficiency',
    title: 'Accuracy and Efficiency',
    subtitle: 'Fewer moves = better score',
    body: [
      'In math, <b>elegance</b> means solving a problem in the fewest steps.',
      '',
      'In this game, that means fewer slider adjustments.',
      '',
      '⭐⭐⭐ = solved with the minimum number of changes',
      'This isn\'t about being fast — it\'s about understanding the math well enough to <b>predict</b> the right answer.',
      '',
      'The best engineers don\'t guess and check. They calculate.',
    ].join('\n'),
    vocabulary: ['efficiency', 'optimization', 'prediction', 'elegant solution'],
  },

  precision_matters: {
    conceptId: 'precision_matters',
    title: 'Precision Matters',
    subtitle: 'Small changes, big effects',
    body: [
      'When structures are complex, a tiny change in one coefficient can mean the difference between hitting and missing.',
      '',
      'This is <b>sensitivity</b> — how much the output changes when you tweak the input.',
      '',
      'Near the vertex, small changes in h barely move the arc.',
      'Near the roots, small changes in r move the landing point a lot.',
      '',
      'Knowing <b>where</b> to be precise is as important as being precise.',
    ].join('\n'),
    vocabulary: ['sensitivity', 'precision', 'tolerance', 'approximation'],
  },

  strategic_thinking: {
    conceptId: 'strategic_thinking',
    title: 'Strategic Thinking',
    subtitle: 'Plan before you launch',
    body: [
      'In timed boss levels, you can\'t afford to guess.',
      '',
      '<b>Read the structure first:</b>',
      '• Where are the weak points? (glass, wood)',
      '• Which block is holding up the target?',
      '• What\'s the simplest arc that reaches it?',
      '',
      'Then set your equation in one or two moves.',
      'Strategic thinking beats random tweaking every time.',
    ].join('\n'),
    vocabulary: ['strategy', 'analysis', 'weak point', 'efficiency'],
  },

  function_transformations: {
    conceptId: 'function_transformations',
    title: 'Function Transformations',
    subtitle: 'The full picture',
    body: [
      'Every coefficient is a <b>transformation</b> of the base function y = x²:',
      '',
      '• <b>a</b>: vertical stretch + reflection',
      '• <b>h</b>: horizontal shift',
      '• <b>k</b>: vertical shift',
      '• <b>r₁, r₂</b>: reframe in terms of roots',
      '• <b>b, c</b>: reframe in terms of intercepts',
      '',
      'All forms are transformations of the same basic shape.',
      'Master the transformations, master the functions.',
    ].join('\n'),
    vocabulary: ['transformation', 'stretch', 'shift', 'reflection'],
  },

  absolute_value_intro: {
    conceptId: 'absolute_value_intro',
    title: 'Absolute Value Functions',
    subtitle: 'y = a|x − h| + k',
    body: [
      'The <b>absolute value</b> makes everything positive.',
      'So |x| creates a V-shape — the left side mirrors the right.',
      '',
      'Unlike a parabola (smooth curve), the V has a <b>sharp corner</b> at the vertex.',
      'That corner is called a <b>non-differentiable point</b> — the slope suddenly changes.',
      '',
      'In the game, absolute value arcs bounce sharply instead of curving smoothly.',
    ].join('\n'),
    vocabulary: ['absolute value', 'V-shape', 'corner point', 'non-differentiable'],
  },

  combining_functions: {
    conceptId: 'combining_functions',
    title: 'Combining Functions',
    subtitle: 'Building complex paths',
    body: [
      'Real paths aren\'t always a single clean equation.',
      '',
      'A basketball shot has: the throw (parabola) + the bounce off the rim (new parabola) + the roll (linear).',
      '',
      'Multi-shot levels let you combine functions — each shot is one piece of the puzzle.',
      'This is how engineers model complex systems: break them into simpler functions, then combine.',
    ].join('\n'),
    vocabulary: ['composition', 'combination', 'modeling', 'systems'],
  },

  math_mastery: {
    conceptId: 'math_mastery',
    title: 'What You\'ve Learned',
    subtitle: 'The full toolkit',
    body: [
      'You\'ve now used:',
      '',
      '• <b>Stretch form</b>: y = ax² — controlling width',
      '• <b>Vertex form</b>: y = a(x−h)² + k — aiming the peak',
      '• <b>Factored form</b>: y = a(x−r₁)(x−r₂) — choosing landing spots',
      '• <b>Standard form</b>: y = ax² + bx + c — reading the y-intercept',
      '• <b>Cubic</b>: y = a(x−h)³ + k — S-curves around obstacles',
      '',
      'These aren\'t just game mechanics. They\'re the same math used in physics, engineering, and computer science.',
    ].join('\n'),
    vocabulary: ['mastery', 'quadratic functions', 'cubic functions', 'applications'],
  },

  piecewise_intro: {
    conceptId: 'piecewise_intro',
    title: 'Piecewise Functions',
    subtitle: 'Different rules for different ranges',
    body: [
      'A <b>piecewise function</b> uses different equations in different parts of the domain.',
      '',
      'Think of it like a recipe: "If x is between 0 and 5, use this arc. If x is between 5 and 10, use that arc."',
      '',
      'Real-world paths often work this way — a ball bounces off a wall and changes direction.',
      'Piecewise functions model that by stitching together simpler functions.',
    ].join('\n'),
    vocabulary: ['piecewise', 'domain', 'continuity', 'junction point'],
  },
};
