// Chapter 7: BEYOND QUADRATICS — cubic, abs value, piecewise
// "Math Machine" mode — different visual treatment. Launcher replaced by grid-based emitter.
// Physics metaphor is explicitly abandoned here.

const LAUNCHER = { x: 1, y: 0.8 };
const THEME = 'space';

export const CHAPTER_7 = [
  {
    id: 'ch7-l1', chapter: 7, levelInChapter: 1,
    title: 'S-Curve',
    equationForm: 'cubic',
    activeCoefficients: ['a', 'h'],
    sliderConfig: {
      a: { min: -0.10, max: 0.10, step: 0.005 },
      h: { min: 1.0,  max: 8.0,  step: 0.1 },
    },
    defaultParams: { a: 0.04, h: 5.0, k: 0 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 8.0, y: 2.5, radius: 0.45, pigType: 'helmet', hp: 1, moving: null }],
    obstacles: [], bonusRing: null,
    starThresholds: [2, 6], starMode: 'moves',
    revealAfter: 'cubic_intro',
    hint: 'Cubic: y = a(x−h)³. S-shaped curve. Positive a rises from left to right.',
    theme: THEME,
  },
  {
    id: 'ch7-l2', chapter: 7, levelInChapter: 2,
    title: 'Loop Around',
    equationForm: 'cubic',
    activeCoefficients: ['a', 'h'],
    sliderConfig: {
      a: { min: -0.10, max: 0.10, step: 0.005 },
      h: { min: 1.0,  max: 8.0,  step: 0.1 },
    },
    defaultParams: { a: 0.05, h: 4.0, k: 0 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 7.0, y: 0.8, radius: 0.45, pigType: 'helmet', hp: 1, moving: null }],
    obstacles: [
      { id: 'ceil', x: 2.0, y: 3.5, width: 5.0, height: 0.3 },
    ],
    bonusRing: null,
    starThresholds: [2, 6], starMode: 'moves',
    revealAfter: null,
    hint: 'Ceiling forces a curve that dips then rises. Cubic can do this.',
    theme: THEME,
  },
  {
    id: 'ch7-l3', chapter: 7, levelInChapter: 3,
    title: 'Negative Cubic',
    equationForm: 'cubic',
    activeCoefficients: ['a', 'h'],
    sliderConfig: {
      a: { min: -0.10, max: 0.10, step: 0.005 },
      h: { min: 1.0,  max: 8.0,  step: 0.1 },
    },
    defaultParams: { a: -0.04, h: 5.0, k: 0 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 5.0, y: 3.5, radius: 0.45, pigType: 'letterman', hp: 1, moving: null }],
    obstacles: [], bonusRing: null,
    starThresholds: [2, 6], starMode: 'moves',
    revealAfter: null,
    hint: 'Negative a flips the S-curve. Falls then rises (from left to right).',
    theme: THEME,
  },
  {
    id: 'ch7-l4', chapter: 7, levelInChapter: 4,
    title: 'V-Shape',
    equationForm: 'abs',
    activeCoefficients: ['a', 'h'],
    sliderConfig: {
      a: { min: -2.0, max: 2.0, step: 0.1 },
      h: { min: 1.0,  max: 8.0, step: 0.1 },
    },
    defaultParams: { a: 0.8, h: 5.0, k: 0 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 7.5, y: 2.5, radius: 0.45, pigType: 'helmet', hp: 1, moving: null }],
    obstacles: [], bonusRing: null,
    starThresholds: [2, 6], starMode: 'moves',
    revealAfter: null,
    hint: 'Absolute value: y = a|x−h|. V-shaped path. Minimum at h.',
    theme: THEME,
  },
  {
    id: 'ch7-l5', chapter: 7, levelInChapter: 5,
    title: 'Bounce Path',
    equationForm: 'abs',
    activeCoefficients: ['a', 'h'],
    sliderConfig: {
      a: { min: -2.0, max: 2.0, step: 0.1 },
      h: { min: 1.0,  max: 8.0, step: 0.1 },
    },
    defaultParams: { a: -1.0, h: 5.0, k: 0 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 8.0, y: 1.5, radius: 0.45, pigType: 'helmet', hp: 1, moving: null }],
    obstacles: [{ id: 'w', x: 5.5, y: 0.8, width: 0.4, height: 2.0 }],
    bonusRing: null,
    starThresholds: [2, 6], starMode: 'moves',
    revealAfter: null,
    hint: 'Negative a: inverted V. Peaks at h. Like a ball bouncing off the ceiling.',
    theme: THEME,
  },
  {
    id: 'ch7-l6', chapter: 7, levelInChapter: 6,
    title: 'Join the Dots',
    equationForm: 'piecewise',
    activeCoefficients: ['a', 'h'],
    sliderConfig: {
      a: { min: -0.45, max: -0.03, step: 0.01 },
      h: { min: 2.0,  max: 7.0,  step: 0.1 },
    },
    defaultParams: {
      a: -0.15, h: 4.5,
      left:  { form: 'standard', params: { a: 0.0, b: 0.8, c: 0 } },
      right: { form: 'vertex',   params: { a: -0.15, h: 0, k: 0 } },
      breakX: 4.5,
      k: 0,
    },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 7.0, y: 2.0, radius: 0.45, pigType: 'letterman', hp: 1, moving: null }],
    obstacles: [], bonusRing: null,
    starThresholds: [2, 6], starMode: 'moves',
    revealAfter: null,
    hint: 'Piecewise: one function left of h, another right. Join point at h.',
    theme: THEME,
  },
  {
    id: 'ch7-l7', chapter: 7, levelInChapter: 7,
    title: 'Mixed Bag',
    equationForm: 'cubic',
    activeCoefficients: ['a', 'h'],
    sliderConfig: {
      a: { min: -0.10, max: 0.10, step: 0.005 },
      h: { min: 1.0,  max: 8.0,  step: 0.1 },
    },
    defaultParams: { a: 0.03, h: 5.5, k: 0 },
    launcher: LAUNCHER,
    targets: [
      { id: 't1', x: 5.5, y: 1.0, radius: 0.40, pigType: 'helmet',    hp: 1, moving: null },
      { id: 't2', x: 8.5, y: 3.5, radius: 0.40, pigType: 'letterman', hp: 1, moving: null },
    ],
    obstacles: [], bonusRing: null,
    starThresholds: [2, 6], starMode: 'moves',
    revealAfter: null,
    hint: 'Cubic passes through two points at different heights simultaneously.',
    theme: THEME,
  },
  {
    id: 'ch7-l8', chapter: 7, levelInChapter: 8,
    title: 'Choose Your Function',
    equationForm: 'vertex',
    activeCoefficients: ['a', 'h'],
    sliderConfig: {
      a: { min: -0.45, max: 0.45, step: 0.01 },
      h: { min: 1.0,  max: 8.0,  step: 0.1 },
    },
    defaultParams: { a: -0.15, h: 4.0, k: 0 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 7.5, y: 1.5, radius: 0.45, pigType: 'king', hp: 1, moving: null }],
    obstacles: [
      { id: 'w1', x: 3.5, y: 0.8, width: 0.4, height: 3.5 },
      { id: 'w2', x: 6.0, y: 2.0, width: 0.4, height: 2.5 },
    ],
    bonusRing: null,
    starThresholds: [2, 6], starMode: 'moves',
    revealAfter: null,
    hint: 'Two walls with narrow gap. Vertex form with the right (a, h) can thread it.',
    theme: THEME,
  },
  {
    id: 'ch7-l9', chapter: 7, levelInChapter: 9,
    title: 'Abs and Conquer',
    equationForm: 'abs',
    activeCoefficients: ['a', 'h'],
    sliderConfig: {
      a: { min: -2.0, max: 2.0, step: 0.1 },
      h: { min: 1.0,  max: 8.0, step: 0.1 },
    },
    defaultParams: { a: 1.2, h: 4.5, k: 0 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 7.5, y: 3.5, radius: 0.45, pigType: 'letterman', hp: 1, moving: null }],
    obstacles: [
      { id: 'ceil', x: 3.0, y: 4.5, width: 5.0, height: 0.3 },
    ],
    bonusRing: null,
    starThresholds: [2, 6], starMode: 'moves',
    revealAfter: null,
    hint: 'Ceiling blocks the top. Absolute value path rises at constant slope — can fit through.',
    theme: THEME,
  },
  {
    id: 'ch7-l10', chapter: 7, levelInChapter: 10,
    title: 'Function Finale',
    equationForm: 'cubic',
    activeCoefficients: ['a', 'h'],
    sliderConfig: {
      a: { min: -0.10, max: 0.10, step: 0.005 },
      h: { min: 1.0,  max: 8.0,  step: 0.1 },
    },
    defaultParams: { a: 0.04, h: 5.0, k: 0 },
    launcher: LAUNCHER,
    targets: [{ id: 'king', x: 8.5, y: 1.5, radius: 0.55, pigType: 'king', hp: 1, moving: null }],
    obstacles: [
      { id: 'w1', x: 3.5, y: 0.8, width: 0.4, height: 2.5 },
      { id: 'w2', x: 6.0, y: 2.5, width: 0.4, height: 2.0 },
    ],
    bonusRing: { x: 4.8, y: 3.8, radius: 0.25 },
    starThresholds: [3, 7], starMode: 'bonus',
    revealAfter: null,
    hint: 'Cubic path, two walls, bonus ring, King Pig. The full beyond-quadratics challenge.',
    theme: THEME,
  },
];
