// Chapter 4: ROOTS — y = a(x−r₁)(x−r₂)
// Factored form. r₁ and r₂ are where the arc crosses y=0 (ground level of launcher).
// Arc starts at local x=0 (launcher). Player controls a, r1, r2.
// Note: the arc starts at local y = a*(0-r1)*(0-r2) = a*r1*r2, not necessarily 0.
// To keep arc starting at launcher: we lock r1=0 in early levels (root at launch = clean start).
// With r1=0: y_local = a*x*(x-r2). This is the 'roots at 0 and r2' setup — arc starts at 0 ✓.

const LAUNCHER = { x: 1, y: 0.8 };
const THEME = 'mountain';

export const CHAPTER_4 = [
  {
    id: 'ch4-l1', chapter: 4, levelInChapter: 1,
    title: 'Ground Zero',
    equationForm: 'factored',
    activeCoefficients: ['a', 'r2'],
    sliderConfig: {
      a:  { min: -0.45, max: -0.02, step: 0.01 },
      r2: { min: 2.0, max: 9.0, step: 0.1 },
    },
    // r1=0 locked: y = a*x*(x-r2). Arc hits ground at local x=r2.
    defaultParams: { a: -0.15, r1: 0, r2: 7.0 },
    launcher: LAUNCHER,
    // Target at ground level — r2 controls landing point directly!
    targets: [{ id: 'main', x: 7.5, y: 0.8, radius: 0.45, pigType: 'helmet', hp: 1, moving: null }],
    obstacles: [], bonusRing: null,
    starThresholds: [2, 5], starMode: 'moves',
    revealAfter: 'factored_form',
    hint: 'r₂ is where the arc lands. Drag it to match the target x-position.',
    theme: THEME,
  },
  {
    id: 'ch4-l2', chapter: 4, levelInChapter: 2,
    title: 'Choose Your Landing',
    equationForm: 'factored',
    activeCoefficients: ['a', 'r2'],
    sliderConfig: {
      a:  { min: -0.45, max: -0.02, step: 0.01 },
      r2: { min: 2.0, max: 9.0, step: 0.1 },
    },
    defaultParams: { a: -0.12, r1: 0, r2: 5.0 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 5.5, y: 0.8, radius: 0.45, pigType: 'helmet', hp: 1, moving: null }],
    obstacles: [], bonusRing: null,
    starThresholds: [2, 5], starMode: 'moves',
    revealAfter: null,
    hint: 'Set r₂ to the target x. Then tune a for the arc height.',
    theme: THEME,
  },
  {
    id: 'ch4-l3', chapter: 4, levelInChapter: 3,
    title: 'On the Way Up',
    equationForm: 'factored',
    activeCoefficients: ['a', 'r2'],
    sliderConfig: {
      a:  { min: -0.45, max: -0.02, step: 0.01 },
      r2: { min: 4.0, max: 9.0, step: 0.1 },
    },
    defaultParams: { a: -0.10, r1: 0, r2: 8.0 },
    launcher: LAUNCHER,
    // Target elevated — arc must be at the right height at the target's x
    targets: [{ id: 'main', x: 4.5, y: 2.5, radius: 0.45, pigType: 'letterman', hp: 1, moving: null }],
    obstacles: [], bonusRing: null,
    starThresholds: [2, 5], starMode: 'moves',
    revealAfter: null,
    hint: 'Target is elevated — the arc passes through it on the way up. r₂ > target x.',
    theme: THEME,
  },
  {
    id: 'ch4-l4', chapter: 4, levelInChapter: 4,
    title: 'Both Roots',
    equationForm: 'factored',
    activeCoefficients: ['a', 'r1', 'r2'],
    sliderConfig: {
      a:  { min: -0.45, max: -0.02, step: 0.01 },
      r1: { min: -1.0, max: 2.0, step: 0.1 },
      r2: { min: 3.0, max: 9.0, step: 0.1 },
    },
    defaultParams: { a: -0.12, r1: 0, r2: 6.5 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 7.5, y: 0.8, radius: 0.45, pigType: 'helmet', hp: 1, moving: null }],
    obstacles: [], bonusRing: null,
    starThresholds: [2, 6], starMode: 'moves',
    revealAfter: null,
    hint: 'Now both roots are free. r₁ shifts the launch offset; r₂ sets the landing.',
    theme: THEME,
  },
  {
    id: 'ch4-l5', chapter: 4, levelInChapter: 5,
    title: 'Wall Bounce',
    equationForm: 'factored',
    activeCoefficients: ['a', 'r1', 'r2'],
    sliderConfig: {
      a:  { min: -0.45, max: -0.02, step: 0.01 },
      r1: { min: -1.0, max: 2.0, step: 0.1 },
      r2: { min: 3.0, max: 9.0, step: 0.1 },
    },
    defaultParams: { a: -0.15, r1: 0, r2: 7.0 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 8.0, y: 0.8, radius: 0.45, pigType: 'helmet', hp: 1, moving: null }],
    obstacles: [{ id: 'w', x: 4.5, y: 0.8, width: 0.4, height: 2.5 }],
    bonusRing: null,
    starThresholds: [2, 5], starMode: 'moves',
    revealAfter: null,
    hint: 'Wall in the way. Set r₂ past the wall so the arc clears it on descent.',
    theme: THEME,
  },
  {
    id: 'ch4-l6', chapter: 4, levelInChapter: 6,
    title: 'Two Landings',
    equationForm: 'factored',
    activeCoefficients: ['a', 'r1', 'r2'],
    sliderConfig: {
      a:  { min: -0.45, max: -0.02, step: 0.01 },
      r1: { min: 0.5, max: 4.0, step: 0.1 },
      r2: { min: 4.0, max: 9.0, step: 0.1 },
    },
    defaultParams: { a: -0.12, r1: 1.0, r2: 7.0 },
    launcher: LAUNCHER,
    // Two ground-level targets — one near r1, one near r2
    targets: [
      { id: 't1', x: 3.0, y: 0.8, radius: 0.40, pigType: 'helmet', hp: 1, moving: null },
      { id: 't2', x: 7.5, y: 0.8, radius: 0.40, pigType: 'helmet', hp: 1, moving: null },
    ],
    obstacles: [], bonusRing: null,
    starThresholds: [2, 6], starMode: 'moves',
    revealAfter: null,
    hint: 'Both roots = both landing points. Set r₁ to hit the first pig, r₂ to hit the second.',
    theme: THEME,
  },
  {
    id: 'ch4-l7', chapter: 4, levelInChapter: 7,
    title: 'Elevated Root',
    equationForm: 'factored',
    activeCoefficients: ['a', 'r1', 'r2'],
    sliderConfig: {
      a:  { min: -0.45, max: -0.02, step: 0.01 },
      r1: { min: -1.0, max: 2.0, step: 0.1 },
      r2: { min: 3.0, max: 9.0, step: 0.1 },
    },
    defaultParams: { a: -0.10, r1: 0, r2: 8.0 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 6.5, y: 2.8, radius: 0.45, pigType: 'letterman', hp: 1, moving: null }],
    obstacles: [{ id: 'plat', x: 5.8, y: 2.5, width: 2.5, height: 0.3 }], // pig sits on platform
    bonusRing: null,
    starThresholds: [2, 6], starMode: 'moves',
    revealAfter: null,
    hint: 'Target on a platform. Arc must be at the right height at that x.',
    theme: THEME,
  },
  {
    id: 'ch4-l8', chapter: 4, levelInChapter: 8,
    title: 'King\'s Court',
    equationForm: 'factored',
    activeCoefficients: ['a', 'r1', 'r2'],
    sliderConfig: {
      a:  { min: -0.45, max: -0.02, step: 0.01 },
      r1: { min: -1.0, max: 2.0, step: 0.1 },
      r2: { min: 3.0, max: 9.0, step: 0.1 },
    },
    defaultParams: { a: -0.14, r1: 0, r2: 7.0 },
    launcher: LAUNCHER,
    targets: [{ id: 'king', x: 8.5, y: 2.0, radius: 0.55, pigType: 'king', hp: 1, moving: null }],
    obstacles: [
      { id: 'w1', x: 4.0, y: 0.8, width: 0.4, height: 2.5 },
      { id: 'w2', x: 6.5, y: 0.8, width: 0.4, height: 1.5 },
    ],
    bonusRing: null,
    starThresholds: [2, 6], starMode: 'moves',
    revealAfter: null,
    hint: 'King Pig on a throne. Two walls. Land r₂ past both walls.',
    theme: THEME,
  },
  {
    id: 'ch4-l9', chapter: 4, levelInChapter: 9,
    title: 'Bonus Ring',
    equationForm: 'factored',
    activeCoefficients: ['a', 'r1', 'r2'],
    sliderConfig: {
      a:  { min: -0.45, max: -0.02, step: 0.01 },
      r1: { min: -1.0, max: 2.0, step: 0.1 },
      r2: { min: 3.0, max: 9.0, step: 0.1 },
    },
    defaultParams: { a: -0.12, r1: 0, r2: 8.5 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 8.5, y: 0.8, radius: 0.45, pigType: 'helmet', hp: 1, moving: null }],
    obstacles: [],
    bonusRing: { x: 5.0, y: 2.8, radius: 0.28 },
    starThresholds: [3, 7], starMode: 'bonus',
    revealAfter: null,
    hint: 'Set r₂=7.5 to land on the pig. Then adjust a so the peak threads the ring for 3★.',
    theme: THEME,
  },
  {
    id: 'ch4-l10', chapter: 4, levelInChapter: 10,
    title: 'Speed Root',
    equationForm: 'factored',
    activeCoefficients: ['a', 'r1', 'r2'],
    sliderConfig: {
      a:  { min: -0.45, max: -0.02, step: 0.01 },
      r1: { min: -1.0, max: 2.0, step: 0.1 },
      r2: { min: 3.0, max: 9.0, step: 0.1 },
    },
    defaultParams: { a: -0.14, r1: 0, r2: 7.5 },
    launcher: LAUNCHER,
    targets: [{
      id: 'cool', x: 7.0, y: 0.8, radius: 0.42, pigType: 'cool', hp: 1,
      moving: { axis: 'x', min: 5.5, max: 8.5, speed: 1.8 },
    }],
    obstacles: [], bonusRing: null,
    starThresholds: [1, 3], starMode: 'moves',
    revealAfter: null,
    hint: 'Moving pig. Set r₂ to where you expect the pig to be when the arc lands.',
    theme: THEME,
  },
];
