// Chapter 5: STANDARD FORM — y = ax² + bx + c
// All three coefficients. c = y-intercept (arc height at launch). b = launch slope.
// Launcher at (1, 0.8). Arc in local coords: y_local = a*x² + b*x + c.
// c=0 means arc starts at launcher height (local y=0). Non-zero c shifts the start.

const LAUNCHER = { x: 1, y: 0.8 };
const THEME = 'space';

export const CHAPTER_5 = [
  {
    id: 'ch5-l1', chapter: 5, levelInChapter: 1,
    title: 'Full Control',
    equationForm: 'standard',
    activeCoefficients: ['a', 'b', 'c'],
    sliderConfig: {
      a: { min: -0.40, max: -0.01, step: 0.01 },
      b: { min:  0.10, max:  3.00, step: 0.05 },
      c: { min: -1.00, max:  1.00, step: 0.05 },
    },
    defaultParams: { a: -0.10, b: 1.0, c: 0 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 7.0, y: 1.5, radius: 0.45, pigType: 'helmet', hp: 1, moving: null }],
    obstacles: [], bonusRing: null,
    starThresholds: [3, 8], starMode: 'moves',
    revealAfter: 'standard_form',
    hint: 'Standard form y=ax²+bx+c. b controls launch angle, c shifts the start height.',
    theme: THEME,
  },
  {
    id: 'ch5-l2', chapter: 5, levelInChapter: 2,
    title: 'Zero Launch',
    equationForm: 'standard',
    activeCoefficients: ['a', 'b'],
    sliderConfig: {
      a: { min: -0.40, max: -0.01, step: 0.01 },
      b: { min:  0.10, max:  3.00, step: 0.05 },
    },
    defaultParams: { a: -0.10, b: 1.2, c: 0 },
    launcher: LAUNCHER,
    // c locked at 0 — arc starts exactly at launcher height
    targets: [{ id: 'main', x: 8.5, y: 0.8, radius: 0.45, pigType: 'helmet', hp: 1, moving: null }],
    obstacles: [], bonusRing: null,
    starThresholds: [2, 6], starMode: 'moves',
    revealAfter: null,
    hint: 'c=0 locked. The arc starts at ground level. Adjust a and b to arc over and land.',
    theme: THEME,
  },
  {
    id: 'ch5-l3', chapter: 5, levelInChapter: 3,
    title: 'Decoder',
    equationForm: 'standard',
    activeCoefficients: ['a', 'b', 'c'],
    sliderConfig: {
      a: { min: -0.40, max: -0.01, step: 0.01 },
      b: { min:  0.10, max:  3.00, step: 0.05 },
      c: { min: -1.00, max:  1.00, step: 0.05 },
    },
    defaultParams: { a: -0.12, b: 1.5, c: 0 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 6.5, y: 3.0, radius: 0.45, pigType: 'letterman', hp: 1, moving: null }],
    obstacles: [], bonusRing: null,
    starThresholds: [3, 8], starMode: 'moves',
    revealAfter: null,
    hint: 'How do a, b, c relate to the vertex position? Experiment.',
    theme: THEME,
  },
  {
    id: 'ch5-l4', chapter: 5, levelInChapter: 4,
    title: 'Constrained',
    equationForm: 'standard',
    activeCoefficients: ['a', 'b', 'c'],
    sliderConfig: {
      a: { min: -0.40, max: -0.01, step: 0.01 },
      b: { min:  0.10, max:  3.00, step: 0.05 },
      c: { min: -1.00, max:  1.00, step: 0.05 },
    },
    defaultParams: { a: -0.15, b: 1.0, c: 0 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 8.0, y: 1.5, radius: 0.40, pigType: 'helmet', hp: 1, moving: null }],
    obstacles: [],
    bonusRing: { x: 4.5, y: 3.5, radius: 0.28 },
    starThresholds: [3, 7], starMode: 'bonus',
    revealAfter: null,
    hint: 'Hit the target AND pass through the ring. Two constraints, three coefficients.',
    theme: THEME,
  },
  {
    id: 'ch5-l5', chapter: 5, levelInChapter: 5,
    title: 'High B',
    equationForm: 'standard',
    activeCoefficients: ['a', 'b', 'c'],
    sliderConfig: {
      a: { min: -0.40, max: -0.01, step: 0.01 },
      b: { min:  1.00, max:  5.00, step: 0.10 },
      c: { min: -1.50, max:  1.50, step: 0.05 },
    },
    defaultParams: { a: -0.08, b: 2.5, c: 0 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 9.0, y: 4.5, radius: 0.45, pigType: 'king', hp: 1, moving: null }],
    obstacles: [
      { id: 'w1', x: 4.0, y: 0.8, width: 0.4, height: 3.0 },
      { id: 'w2', x: 6.5, y: 0.8, width: 0.4, height: 2.0 },
    ],
    bonusRing: null,
    starThresholds: [2, 7], starMode: 'moves',
    revealAfter: null,
    hint: 'High b = steep launch angle. Two walls, very high target.',
    theme: THEME,
  },
  {
    id: 'ch5-l6', chapter: 5, levelInChapter: 6,
    title: 'Three Forms',
    equationForm: 'standard',
    activeCoefficients: ['a', 'b', 'c'],
    sliderConfig: {
      a: { min: -0.40, max: -0.01, step: 0.01 },
      b: { min:  0.10, max:  3.00, step: 0.05 },
      c: { min: -1.00, max:  1.00, step: 0.05 },
    },
    defaultParams: { a: -0.12, b: 1.2, c: 0.5 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 7.5, y: 2.0, radius: 0.42, pigType: 'helmet', hp: 1, moving: null }],
    obstacles: [],
    bonusRing: { x: 3.5, y: 2.8, radius: 0.28 },
    starThresholds: [3, 7], starMode: 'bonus',
    revealAfter: null,
    hint: 'c shifts the launch height. Non-zero c means the arc starts above or below ground.',
    theme: THEME,
  },
  {
    id: 'ch5-l7', chapter: 5, levelInChapter: 7,
    title: 'Moving Standard',
    equationForm: 'standard',
    activeCoefficients: ['a', 'b', 'c'],
    sliderConfig: {
      a: { min: -0.40, max: -0.01, step: 0.01 },
      b: { min:  0.10, max:  3.00, step: 0.05 },
      c: { min: -1.00, max:  1.00, step: 0.05 },
    },
    defaultParams: { a: -0.10, b: 1.5, c: 0 },
    launcher: LAUNCHER,
    targets: [{
      id: 'cool', x: 7.0, y: 1.5, radius: 0.42, pigType: 'cool', hp: 1,
      moving: { axis: 'x', min: 5.5, max: 8.5, speed: 1.2 },
    }],
    obstacles: [], bonusRing: null,
    starThresholds: [1, 4], starMode: 'moves',
    revealAfter: null,
    hint: 'Moving target. Standard form gives you more control over the trajectory shape.',
    theme: THEME,
  },
  {
    id: 'ch5-l8', chapter: 5, levelInChapter: 8,
    title: 'Obstacle Course',
    equationForm: 'standard',
    activeCoefficients: ['a', 'b', 'c'],
    sliderConfig: {
      a: { min: -0.40, max: -0.01, step: 0.01 },
      b: { min:  0.10, max:  3.00, step: 0.05 },
      c: { min: -1.00, max:  1.00, step: 0.05 },
    },
    defaultParams: { a: -0.14, b: 1.5, c: 0 },
    launcher: LAUNCHER,
    targets: [{ id: 'main', x: 8.5, y: 1.0, radius: 0.42, pigType: 'helmet', hp: 1, moving: null }],
    obstacles: [
      { id: 'w1', x: 3.0, y: 0.8, width: 0.4, height: 2.8 },
      { id: 'w2', x: 5.5, y: 2.5, width: 0.4, height: 2.0 },
      { id: 'w3', x: 7.5, y: 0.8, width: 0.4, height: 1.8 },
    ],
    bonusRing: null,
    starThresholds: [2, 6], starMode: 'moves',
    revealAfter: null,
    hint: 'Three obstacles. Standard form lets you tune entry angle (b) and height offset (c).',
    theme: THEME,
  },
  {
    id: 'ch5-l9', chapter: 5, levelInChapter: 9,
    title: 'Equivalent Forms',
    equationForm: 'standard',
    activeCoefficients: ['a', 'b', 'c'],
    sliderConfig: {
      a: { min: -0.40, max: -0.01, step: 0.01 },
      b: { min:  0.50, max:  4.00, step: 0.05 },
      c: { min: -2.00, max:  2.00, step: 0.05 },
    },
    defaultParams: { a: -0.12, b: 2.0, c: -0.5 },
    launcher: LAUNCHER,
    targets: [
      { id: 't1', x: 5.5, y: 2.5, radius: 0.40, pigType: 'helmet', hp: 1, moving: null },
      { id: 't2', x: 9.0, y: 0.8, radius: 0.40, pigType: 'helmet', hp: 1, moving: null },
    ],
    obstacles: [], bonusRing: null,
    starThresholds: [2, 6], starMode: 'moves',
    revealAfter: null,
    hint: 'Hit both pigs. One arc, two targets — standard form gives maximum flexibility.',
    theme: THEME,
  },
  {
    id: 'ch5-l10', chapter: 5, levelInChapter: 10,
    title: 'Grand Standard',
    equationForm: 'standard',
    activeCoefficients: ['a', 'b', 'c'],
    sliderConfig: {
      a: { min: -0.40, max: -0.01, step: 0.01 },
      b: { min:  0.10, max:  4.00, step: 0.05 },
      c: { min: -2.00, max:  2.00, step: 0.05 },
    },
    defaultParams: { a: -0.10, b: 1.8, c: 0 },
    launcher: LAUNCHER,
    targets: [{ id: 'king', x: 8.5, y: 3.0, radius: 0.55, pigType: 'king', hp: 1, moving: null }],
    obstacles: [
      { id: 'w1', x: 3.5, y: 0.8, width: 0.4, height: 2.5 },
      { id: 'w2', x: 6.0, y: 2.0, width: 0.4, height: 2.5 },
    ],
    bonusRing: { x: 5.0, y: 4.0, radius: 0.25 },
    starThresholds: [3, 8], starMode: 'bonus',
    revealAfter: null,
    hint: 'King Pig. Two walls. Bonus ring near the peak. All three coefficients needed.',
    theme: THEME,
  },
];
